# Generated by Django 4.0.2 on 2022-04-13 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_ticket_event_alter_event_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='name',
        ),
    ]
