# Generated by Django 4.0.2 on 2022-04-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_ticket_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='slug',
            field=models.SlugField(default='hello-dis'),
            preserve_default=False,
        ),
    ]
