# Generated by Django 4.0.2 on 2023-01-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_tickettype_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
