# Generated by Django 4.0.2 on 2023-01-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_tickettype_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(default="27513821", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default="1263-12-3"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='location_latitude',
            field=models.FloatField(default=217358.00),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='location_longitude',
            field=models.FloatField(default=213323.00),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(default="12:31"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
