# Generated by Django 4.0.2 on 2023-01-20 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_address_event_date_event_location_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickettype',
            old_name='limit',
            new_name='amount',
        ),
    ]
